### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Florian95** [BrainMaestro/elixir-phoenix-realworld#16]
Hi,

I would like to work on this project. To improve my Elixir / Phoenix skills and maybe share things with the community.

I thought I'd start by setting up the authentication feature.

Short list :
- [Coherence](https://github.com/smpallen99/coherence)
- [Guardian](https://github.com/ueberauth/guardian)
- [Ueberauth](https://github.com/ueberauth/ueberauth)

I think `Guardian` should be the best choice. Very straight forward, JWT, few dependencies.

What do you think ?

Florian

**Comment by BrainMaestro** [comment]
Sure, most people seem to like Guardian as well. No one else is working on this, so go ahead. 👍

**Comment by Florian95** [comment]
First commit : https://github.com/BrainMaestro/elixir-phoenix-realworld/compare/master...Florian95:feature/auth

[Postman test API](https://github.com/gothinkster/realworld/tree/master/api) :

Path | Status
------------ | -------------
`POST /api/users` | ✅ 
`POST /api/users/login` | ✅ 
`GET /api/user` with JWT check | ✅ 
`PUT /api/user` with JWT check | ✅ 

Phoenix tests are OK too.

Any feedbacks ?
