### ISSUE TITLE
Elixir only backend? 

### ISSUE THREAD

**Issue by omidfi** [BrainMaestro/elixir-phoenix-realworld#18]
Hi, 
I don't know much Elixir. But I was thinking it would be awesome to mix Elixir and Elm. 
How much work is it to take only thr elixir api out of this repo and make it independent of phonix? 

Is anyone willing to help?

**Comment by fcevado** [comment]
@omidfi this is how the RealWorld project works. Isolated implementations of back end and front end. There is a Elm implementation created by Richard Feldman
https://github.com/rtfeldman/elm-spa-example

**Comment by omidfi** [comment]
Yes I know about the elm. But is there an isolated Elixir backend? 

As far as I can tell, this project (BrainMaestro/elixir-phoenix-realworld) is also outputting the view, meaning it's both the backend and frontend.

**Comment by fcevado** [comment]
> **this is how the RealWorld project works. Isolated implementations of back end and front end.**

Or from the [issue](https://github.com/gothinkster/realworld/issues/17#issuecomment-296896203) in the original repo:

> Nope, this is **strictly API** requests only

**Comment by BrainMaestro** [comment]
@omidfi, like @fcevado said, we only do API requests that return json.

**Comment by omidfi** [comment]
Ok my bad :) The Views folder foolde me to believe this is thd full stack.

**Comment by fcevado** [comment]
@omidfi in Phoenix, views are more like "helpers"... the "view" folder is template.
