### ISSUE TITLE
namespace problem again (realword instead of realWorld)

### ISSUE THREAD

**Issue by supernova23** [BrainMaestro/elixir-phoenix-realworld#4]
newly generated code use the old namespace Realworld instead of RealWorld

![dddd](https://cloud.githubusercontent.com/assets/8417751/25414268/8e039ef8-2a28-11e7-8f58-eb79438e6a9a.png)

**Comment by agustif** [comment]
I wouldn't sweat it and just reset this repo to a newly generated directly in 1.3rc with the correct namespace and be done with it
